### ISSUE TITLE
ToDo

### ISSUE THREAD

**Issue by McDiod** [gruppe-adler/grad-moneyMenu#1]
- [x] take from dead units
- [x] store in containers (safe + unsafe)
- [x] bank accounts + atms
- [x] functions to set parameters
- [x] test MP
